## Team ID: PNT2022TMID43387

###  Importing the required libraries

In [ ]:
import numpy as np
import tensorflow #both ML and DL for computation
from tensorflow.keras.datasets import mnist #mnist dataset
from tensorflow.keras.models import Sequential #plain stack of layers
from tensorflow.keras import layers #A Layer consists of a tensor- in tensor-out computation function
from tensorflow.keras.layers import Dense, Flatten #dense and flatten layers
from tensorflow.keras.layers import Conv2D #convoLutional Layer
from tensorflow.keras.layers import MaxPooling2D 
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Dropout
from keras.optimizers import Adam #optimizer
from keras. utils import np_utils #used for one-hot encoding
import matplotlib.pyplot as plt   #used for data visualization

### Data preprocessing

In [ ]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

#CNN expected format: (batch,height,width,channel)
x_train=x_train.reshape(60000,28,28,1).astype('float32')
x_test=x_test.reshape(10000,28,28,1).astype('float32')
no_of_classes=10
y_train=np_utils.to_categorical(y_train,no_of_classes) #converts output to binary format
y_test=np_utils.to_categorical(y_test,no_of_classes)

### Add CNN Layers

In [ ]:
#create model
model = Sequential()
model.add(Conv2D(32, kernel_size = 3, activation='relu', input_shape=(28, 28, 1)))
model.add(MaxPooling2D())
model.add(Conv2D(32, kernel_size = 3, activation='relu'))
model.add(BatchNormalization())
model.add(Conv2D(32, kernel_size = 5, strides=2, padding='same', activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.4))
model.add(Conv2D(64, kernel_size = 3, activation='relu'))
model.add(BatchNormalization())
model.add(Conv2D(64, kernel_size = 3, activation='relu'))
model.add(BatchNormalization())
model.add(Conv2D(64, kernel_size = 5, strides=2, padding='same', activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.4))
model.add(Flatten())
model.add(Dropout(0.4))
model.add(Dense(10, activation='softmax'))

### Compiling the model

In [ ]:
#Compile model
model.compile(loss= 'categorical_crossentropy', optimizer="Adam", metrics=['accuracy'])

Compilation requires 3 arguments: an optimizer, a loss function, and a list of metrics.
In our project, we have 2 classes in the output, so the loss is binary_crossentropy.
If you have more than two classes in output put “loss = categorical_cross entropy”. 

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 32)        9248      
                                                                 
 batch_normalization (BatchN  (None, 11, 11, 32)       128       
 ormalization)                                                   
                                                                 
 conv2d_2 (Conv2D)           (None, 6, 6, 32)          25632     
                                                                 
 batch_normalization_1 (Batc  (None, 6, 6, 32)         1

In [ ]:
x_train = np.asarray(x_train)
y_train = np.asarray(y_train)

### Train the model

In [ ]:
#fit the model
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=10, batch_size=32)

Epoch 1/10
1875/1875 [==============================] - 78s 39ms/step - loss: 0.2815 - accuracy: 0.9210 - val_loss: 0.0508 - val_accuracy: 0.9841
Epoch 2/10
1875/1875 [==============================] - 70s 37ms/step - loss: 0.1037 - accuracy: 0.9722 - val_loss: 0.0305 - val_accuracy: 0.9899
Epoch 3/10
1875/1875 [==============================] - 69s 37ms/step - loss: 0.0818 - accuracy: 0.9789 - val_loss: 0.0329 - val_accuracy: 0.9903
Epoch 4/10
1875/1875 [==============================] - 69s 37ms/step - loss: 0.0669 - accuracy: 0.9820 - val_loss: 0.0495 - val_accuracy: 0.9866
Epoch 5/10
1875/1875 [==============================] - 69s 37ms/step - loss: 0.0583 - accuracy: 0.9841 - val_loss: 0.0249 - val_accuracy: 0.9931
Epoch 6/10
1875/1875 [==============================] - 69s 37ms/step - loss: 0.0500 - accuracy: 0.9869 - val_loss: 0.0251 - val_accuracy: 0.9930
Epoch 7/10
1875/1875 [==============================] - 71s 38ms/step - loss: 0.0436 - accuracy: 0.9886 - val_loss: 0.0296 -

Arguments:
steps_per_epoch : it specifies the total number of steps taken from the generator as soon as one epoch is finished and the next epoch has started. We can calculate the value of steps_per_epoch as the total number of samples in your dataset divided by the batch size.

Epochs: an integer and number of epochs we want to train our model for.

Validation_data :  
an inputs and targets list
a generator
inputs, targets, and sample_weights list which can be used to evaluate the loss and metrics for any model after any epoch has ended.


validation_steps: only if the validation_data is a generator then only this argument can be used. It specifies the total number of steps taken from the generator before it is stopped at every epoch and its value is calculated as the total number of validation data points in your dataset divided by the validation batch size.

### Observing the metrics

In [ ]:
#final evaluation of the model
metrics = model.evaluate(x_test, y_test, verbose=0)
print("Metrics(Test loss & Test Accuracy) : ")
print(metrics)

Metrics(Test loss & Test Accuracy) : 
[0.01923108845949173, 0.9944999814033508]


### Test the model

In [ ]:
prediction=model.predict(x_test[:4])
print(prediction)

1/1 [==============================] - 1s 527ms/step
[[2.39270328e-08 1.90741822e-08 7.76825502e-08 7.92453818e-08
  1.60290128e-07 8.87892284e-08 5.42882894e-08 9.99998927e-01
  3.91918391e-08 4.17797168e-07]
 [3.15403099e-08 2.42661963e-06 9.99994159e-01 2.56797648e-07
  2.86123537e-07 3.25858707e-07 5.51403957e-07 1.65956305e-06
  1.44440563e-07 1.45353255e-07]
 [6.46729026e-09 9.99997735e-01 7.00532439e-07 1.33116259e-07
  3.17947865e-07 1.37819669e-07 1.45124972e-07 6.46433705e-07
  6.51577992e-08 2.81121935e-08]
 [9.99997020e-01 2.82281238e-08 2.18443947e-08 7.75419551e-07
  1.87574969e-07 1.09308885e-07 8.58419298e-07 1.70689304e-07
  1.90090361e-07 6.41211841e-07]]


In [ ]:
print(np.argmax(prediction,axis=1)) #printing labels from first 4 images
print(y_test[:4]) #printing the actual labels

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


As we already predicted the input from the x_test. According to that by using argmax function here we are printing the labels with high prediction values 

### Saving the model

In [ ]:
#save the model
model.save('models/mnistCNN1.h5')

The model is saved with .h5 extension as follows:
An H5 file is a data file saved in the Hierarchical Data Format (HDF). It contains multidimensional arrays of scientific data.

In [ ]:
# Saving in tar

!tar -zcvf digitrecmodel.tgz --absolute-names /content/models/mnistCNN1.h5

/content/models/mnistCNN1.h5


In [ ]:
!pip install watson-machine-learning-client

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 538 kB 4.4 MB/s 
     |████████████████████████████████| 55 kB 3.3 MB/s 
     |████████████████████████████████| 132 kB 55.5 MB/s 
     |████████████████████████████████| 79 kB 6.7 MB/s 
     |████████████████████████████████| 9.9 MB 44.9 MB/s 
     |████████████████████████████████| 140 kB 75.8 MB/s 
     |████████████████████████████████| 956 kB 40.9 MB/s 
     |████████████████████████████████| 135 kB 54.7 MB/s 
     |████████████████████████████████| 62 kB 1.5 MB/s 
  Created wheel for ibm-cos-sdk: filename=ibm_cos_sdk-2.12.0-py3-none-any.whl size=73931 sha256=4dd5d28bd1c116caa427a49c959e4d4a0d14c7182889983437b27b88c0dac3ff
  Stored in directory: /root/.cache/pip/wheels/ec/94/29/2b57327cf00664b6614304f7958abd29d77ea0e5bbece2ea57
  Created wheel for ibm-cos-sdk-core: filename=ibm_cos_sdk_core-2.12.0-py3-none-any.whl size=562962 sha256=70e7c1f9305

In [ ]:
!pip install ibm_watson_machine_learning

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.8 MB 4.4 MB/s 
     |████████████████████████████████| 51 kB 654 kB/s 
     |████████████████████████████████| 824 kB 47.5 MB/s 
     |████████████████████████████████| 133 kB 44.8 MB/s 
     |████████████████████████████████| 547 kB 55.5 MB/s 
  Created wheel for ibm-cos-sdk: filename=ibm_cos_sdk-2.7.0-py2.py3-none-any.whl size=72563 sha256=9d4b683e665166fd20b6f4f381f92d56932ed8c47a82050b828a6a9528eb2be3
  Stored in directory: /root/.cache/pip/wheels/47/22/bf/e1154ff0f5de93cc477acd0ca69abfbb8b799c5b28a66b44c2
  Created wheel for ibm-cos-sdk-core: filename=ibm_cos_sdk_core-2.7.0-py2.py3-none-any.whl size=501013 sha256=b4eb4c674be520e641df197e04d4503450c8070a570d624ee8470ac2b7df9c2d
  Stored in directory: /root/.cache/pip/wheels/6c/a2/e4/c16d02f809a3ea998e17cfd02c13369281f3d232aaf5902c19
  Created wheel for ibm-cos-sdk-s3transfer: filename=ibm_cos_

In [ ]:
from ibm_watson_machine_learning import APIClient

wml_credentials ={
    "url":"https://eu-gb.ml.cloud.ibm.com",
    "apikey":"ZcbwcMahQ_rkhcVB9ruUffQ-NZ-897oTRQTlHjO45fHy"
}

client = APIClient(wml_credentials)
client

Python 3.7 and 3.8 frameworks are deprecated and will be removed in a future release. Use Python 3.9 framework instead.


In [ ]:
client.spaces.get_details()

{'resources': [{'entity': {'compute': [{'crn': 'crn:v1:bluemix:public:pm-20:eu-gb:a/f14a77084b1c485d89784cfe5e973214:9068724d-f4ab-4181-86fe-5e1cff47a5fe::',
      'guid': '9068724d-f4ab-4181-86fe-5e1cff47a5fe',
      'name': 'Watson Machine Learning-ic',
      'type': 'machine_learning'}],
    'description': '',
    'name': 'ibm',
    'scope': {'bss_account_id': 'f14a77084b1c485d89784cfe5e973214'},
    'stage': {'production': False},
    'status': {'state': 'active'},
    'storage': {'properties': {'bucket_name': '0ba62238-0825-4752-be1a-19bce9957408',
      'bucket_region': 'eu-gb-standard',
      'credentials': {'admin': {'access_key_id': '066b75e06c79437eb23cb09a926361e5',
        'api_key': '_Veu3xMgjahsKrO757_Tm8zB1wjJrL4iz9SRrQvsYekW',
        'secret_access_key': '6bf7925cee97c695fb744a92c3684c0c10aa37ed8e6f333b',
        'service_id': 'ServiceId-8fc34dfe-1255-4f80-8dc3-09015b9a7e7d'},
       'editor': {'access_key_id': '21f3cab482f54962af311db9eea1afb7',
        'api_key': 'kv

In [ ]:
def guid_space_name(client,name):
  space = client.spaces.get_details()
  return(next(item for item in space['resources'] if item['entity']['name']==name)['metadata']['id'])

In [ ]:
space_uid = guid_space_name(client,'ibm')
space_uid

'cceb28ee-c6e6-46d4-9b6e-c4787c9c4a78'

In [ ]:
client.set.default_space(space_uid)

'SUCCESS'

In [ ]:
client.software_specifications.list()

-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
kernel-spark3.2-scala2.12      020d69ce-7ac1-5e68-ac1a-31189867356a  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
pytorch-onnx_rt22.1-py3.9      0b848dd4-e681-5599-be41-b5f6fccc6471  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
tensorflow_2.4-py3.7-horovod   1092590a-307d-563d-9b62-4eb7d64b3f22  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl      111e41b3-de2d-5422-a4d6-bf776828c4b7  base
autoai-kb_rt22.2-py3.10        125b6d9

In [ ]:
software_space_uid = client.software_specifications.get_uid_by_name('tensorflow_rt22.1-py3.9')
software_space_uid

'acd9c798-6974-5d2f-a657-ce06e986df4d'

In [ ]:
model_details = client.repository.store_model(model='digitrecmodel.tgz',meta_props={
    client.repository.ModelMetaNames.NAME:"ibm",
    client.repository.ModelMetaNames.TYPE:"tensorflow_2.7",
    client.repository.ModelMetaNames.SOFTWARE_SPEC_UID:software_space_uid
})

In [ ]:
model_details

{'entity': {'hybrid_pipeline_software_specs': [],
  'software_spec': {'id': 'acd9c798-6974-5d2f-a657-ce06e986df4d',
   'name': 'tensorflow_rt22.1-py3.9'},
  'type': 'tensorflow_2.7'},
 'metadata': {'created_at': '2022-11-19T09:20:20.023Z',
  'id': '9b0b65e4-9f35-426e-961f-15f8b741fe97',
  'modified_at': '2022-11-19T09:20:25.668Z',
  'name': 'ibm',
  'owner': 'IBMid-66200444KQ',
  'resource_key': 'ffff3a56-dfd1-492e-8ced-ed8628d6acff',
  'space_id': 'cceb28ee-c6e6-46d4-9b6e-c4787c9c4a78'},
 'system': {'warnings': []}}

In [ ]:
model_id = client.repository.get_model_id(model_details)
model_id

'9b0b65e4-9f35-426e-961f-15f8b741fe97'

In [ ]:
client.repository.download(model_id,'fetch.tar.gb')

Successfully saved model content to file: 'fetch.tar.gb'


'/content/fetch.tar.gb'