# Sprint 2

## Team ID: PNT2022TMID43387

###  Importing the required libraries

In [1]:
import numpy as np
import tensorflow #both ML and DL for computation
from tensorflow.keras.datasets import mnist #mnist dataset
from tensorflow.keras.models import Sequential #plain stack of layers
from tensorflow.keras import layers #A Layer consists of a tensor- in tensor-out computat ion funct ion
from tensorflow.keras.layers import Dense, Flatten #dense and flatten layers
from tensorflow.keras.layers import Conv2D #onvoLutiona l Layer
from tensorflow.keras.layers import MaxPooling2D 
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Dropout
from keras.optimizers import Adam #optimizer
from keras. utils import np_utils #used for one-hot encoding
import matplotlib.pyplot as plt   #used for data visualization

### Data preprocessing - Sprint 1

In [2]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

#CNN expected format: (batch,height,width,channel)
x_train=x_train.reshape(60000,28,28,1).astype('float32')
x_test=x_test.reshape(10000,28,28,1).astype('float32')
no_of_classes=10
y_train=np_utils.to_categorical(y_train,no_of_classes) #converts output to binary format
y_test=np_utils.to_categorical(y_test,no_of_classes)

### Add CNN Layers

In [3]:
#create model
model = Sequential()
model.add(Conv2D(32, kernel_size = 3, activation='relu', input_shape=(28, 28, 1)))
model.add(MaxPooling2D())
model.add(Conv2D(32, kernel_size = 3, activation='relu'))
model.add(BatchNormalization())
model.add(Conv2D(32, kernel_size = 5, strides=2, padding='same', activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.4))
model.add(Conv2D(64, kernel_size = 3, activation='relu'))
model.add(BatchNormalization())
model.add(Conv2D(64, kernel_size = 3, activation='relu'))
model.add(BatchNormalization())
model.add(Conv2D(64, kernel_size = 5, strides=2, padding='same', activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.4))
model.add(Flatten())
model.add(Dropout(0.4))
model.add(Dense(10, activation='softmax'))

### Compiling the model

In [4]:
#Compile model
model.compile(loss= 'categorical_crossentropy', optimizer="Adam", metrics=['accuracy'])

Compilation requires 3 arguments: an optimizer, a loss function, and a list of metrics.
In our project, we have 2 classes in the output, so the loss is binary_crossentropy.
If you have more than two classes in output put “loss = categorical_cross entropy”. 

In [5]:
x_train = np.asarray(x_train)
y_train = np.asarray(y_train)

### Train the model

In [6]:
#fit the model
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=10, batch_size=32)

Epoch 1/10
1875/1875 [==============================] - 78s 39ms/step - loss: 0.2815 - accuracy: 0.9210 - val_loss: 0.0508 - val_accuracy: 0.9841
Epoch 2/10
1875/1875 [==============================] - 70s 37ms/step - loss: 0.1037 - accuracy: 0.9722 - val_loss: 0.0305 - val_accuracy: 0.9899
Epoch 3/10
1875/1875 [==============================] - 69s 37ms/step - loss: 0.0818 - accuracy: 0.9789 - val_loss: 0.0329 - val_accuracy: 0.9903
Epoch 4/10
1875/1875 [==============================] - 69s 37ms/step - loss: 0.0669 - accuracy: 0.9820 - val_loss: 0.0495 - val_accuracy: 0.9866
Epoch 5/10
1875/1875 [==============================] - 69s 37ms/step - loss: 0.0583 - accuracy: 0.9841 - val_loss: 0.0249 - val_accuracy: 0.9931
Epoch 6/10
1875/1875 [==============================] - 69s 37ms/step - loss: 0.0500 - accuracy: 0.9869 - val_loss: 0.0251 - val_accuracy: 0.9930
Epoch 7/10
1875/1875 [==============================] - 71s 38ms/step - loss: 0.0436 - accuracy: 0.9886 - val_loss: 0.0296 -

Arguments:
steps_per_epoch : it specifies the total number of steps taken from the generator as soon as one epoch is finished and the next epoch has started. We can calculate the value of steps_per_epoch as the total number of samples in your dataset divided by the batch size.

Epochs: an integer and number of epochs we want to train our model for.

Validation_data :  
an inputs and targets list
a generator
inputs, targets, and sample_weights list which can be used to evaluate the loss and metrics for any model after any epoch has ended.


validation_steps: only if the validation_data is a generator then only this argument can be used. It specifies the total number of steps taken from the generator before it is stopped at every epoch and its value is calculated as the total number of validation data points in your dataset divided by the validation batch size.

### Observing the metrics

In [7]:
#final evaluation of the model
metrics = model.evaluate(x_test, y_test, verbose=0)
print("Metrics(Test loss & Test Accuracy) : ")
print(metrics)

Metrics(Test loss & Test Accuracy) : 
[0.01923108845949173, 0.9944999814033508]


### Test the model

In [8]:
prediction=model.predict(x_test[:4])
print(prediction)

1/1 [==============================] - 1s 527ms/step
[[2.39270328e-08 1.90741822e-08 7.76825502e-08 7.92453818e-08
  1.60290128e-07 8.87892284e-08 5.42882894e-08 9.99998927e-01
  3.91918391e-08 4.17797168e-07]
 [3.15403099e-08 2.42661963e-06 9.99994159e-01 2.56797648e-07
  2.86123537e-07 3.25858707e-07 5.51403957e-07 1.65956305e-06
  1.44440563e-07 1.45353255e-07]
 [6.46729026e-09 9.99997735e-01 7.00532439e-07 1.33116259e-07
  3.17947865e-07 1.37819669e-07 1.45124972e-07 6.46433705e-07
  6.51577992e-08 2.81121935e-08]
 [9.99997020e-01 2.82281238e-08 2.18443947e-08 7.75419551e-07
  1.87574969e-07 1.09308885e-07 8.58419298e-07 1.70689304e-07
  1.90090361e-07 6.41211841e-07]]


In [9]:
print(np.argmax(prediction,axis=1)) #printing labels from first 4 images
print(y_test[:4]) #printing the actual labels

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


As we already predicted the input from the x_test. According to that by using argmax function here we are printing the labels with high prediction values 

### Saving the model

In [10]:
#save the model
model.save('models/mnistCNN1.h5')

The model is saved with .h5 extension as follows:
An H5 file is a data file saved in the Hierarchical Data Format (HDF). It contains multidimensional arrays of scientific data.